/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cl.edbray.pnb.gui;

import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author eduardo
 */
public class EventsPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventsPanel
     */
    public EventsPanel() {
        initComponents();
        setupComponents();
    }

    private void setupComponents() {
        setLayout(new GridBagLayout());

        JLabel lblTitle = new JLabel(
            "<html><center>" +
            "<h1 style='color: #FC2270;'>🎮 Eventos y Torneos</h1>" +
            "<p style='margin-top: 20px; font-size: 14px;'>" +
            "Este módulo está en desarrollo y estará disponible próximamente." +
            "</p>" +
            "<p style='margin-top: 30px; font-size: 12px; color: #aaa;'>" +
            "Funcionalidades planificadas:" +
            "</p>" +
            "<ul style='text-align: left; font-size: 12px; color: #aaa;'>" +
            "<li>Gestión de torneos semanales</li>" +
            "<li>Inscripción de participantes</li>" +
            "<li>Registro de resultados</li>" +
            "<li>Rankings y estadísticas</li>" +
            "</ul>" +
            "</center></html>"
        );

        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
        add(lblTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}