/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.edbray.pnb.gui;

import cl.edbray.pnb.app.ApplicationContext;
import cl.edbray.pnb.controller.LoginController;
import cl.edbray.pnb.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardo
 */
public class LoginFrame extends javax.swing.JFrame {
    private LoginController controller;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        controller = ApplicationContext.getInstance().getLoginController();

        initComponents();
        getRootPane().setDefaultButton(loginButton);
    }

    private void startMain(User user) {
        MainFrame main = new MainFrame(user);
        main.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        rightPanelLeftPadding = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        rightPanelRightPadding = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        rightPanelBottomPadding = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        fieldsContainer = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleTopPadding = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        title = new javax.swing.JLabel();
        titleSeparator = new javax.swing.JSeparator();
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        buttonsPanel = new javax.swing.JPanel();
        buttonsTopPadding = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        buttonsRowPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        buttonsBottomPadding = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pixel & Bean – Login");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        mainPanel.setLayout(new java.awt.GridLayout(1, 2));

        leftPanel.setBackground(new java.awt.Color(0, 0, 0));
        leftPanel.setLayout(new java.awt.GridLayout(1, 1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png")));
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logo.setMaximumSize(new java.awt.Dimension(400, 500));
        logo.setMinimumSize(new java.awt.Dimension(400, 500));
        leftPanel.add(logo);

        mainPanel.add(leftPanel);

        rightPanel.setBackground(new java.awt.Color(42, 42, 42));
        rightPanel.setLayout(new java.awt.BorderLayout(25, 25));
        rightPanel.add(rightPanelLeftPadding, java.awt.BorderLayout.WEST);
        rightPanel.add(rightPanelRightPadding, java.awt.BorderLayout.EAST);
        rightPanel.add(rightPanelBottomPadding, java.awt.BorderLayout.PAGE_END);

        fieldsContainer.setBackground(new java.awt.Color(42, 42, 42));
        fieldsContainer.setLayout(new java.awt.GridLayout(4, 0));

        titlePanel.setBackground(new java.awt.Color(42, 42, 42));
        titlePanel.setLayout(new java.awt.GridLayout(3, 0));
        titlePanel.add(titleTopPadding);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(52, 184, 209));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Le damos la bienvenida");
        titlePanel.add(title);

        titleSeparator.setForeground(new java.awt.Color(52, 184, 209));
        titlePanel.add(titleSeparator);

        fieldsContainer.add(titlePanel);

        usernamePanel.setBackground(new java.awt.Color(42, 42, 42));
        usernamePanel.setLayout(new java.awt.GridLayout(2, 1, 0, 15));

        usernameLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(252, 26, 112));
        usernameLabel.setText("Nombre de usuario:");
        usernameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        usernamePanel.add(usernameLabel);

        usernameField.setBackground(new java.awt.Color(68, 68, 68));
        usernameField.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        usernameField.setForeground(new java.awt.Color(240, 240, 240));
        usernameField.setAutoscrolls(false);
        usernameField.setCaretColor(new java.awt.Color(244, 244, 244));
        usernameField.setMargin(new java.awt.Insets(2, 10, 2, 10));
        usernameField.setVerifyInputWhenFocusTarget(false);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        usernamePanel.add(usernameField);

        fieldsContainer.add(usernamePanel);

        passwordPanel.setBackground(new java.awt.Color(42, 42, 42));
        passwordPanel.setLayout(new java.awt.GridLayout(2, 1, 0, 15));

        passwordLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(252, 26, 112));
        passwordLabel.setText("Contraseña:");
        passwordLabel.setToolTipText("");
        passwordLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        passwordPanel.add(passwordLabel);

        passwordField.setBackground(new java.awt.Color(68, 68, 68));
        passwordField.setForeground(new java.awt.Color(240, 240, 240));
        passwordField.setCaretColor(new java.awt.Color(244, 244, 244));
        passwordField.setMargin(new java.awt.Insets(2, 10, 2, 10));
        passwordPanel.add(passwordField);

        fieldsContainer.add(passwordPanel);

        buttonsPanel.setBackground(new java.awt.Color(42, 42, 42));
        buttonsPanel.setLayout(new java.awt.GridLayout(3, 1));
        buttonsPanel.add(buttonsTopPadding);

        buttonsRowPanel.setBackground(new java.awt.Color(42, 42, 42));
        buttonsRowPanel.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        loginButton.setBackground(new java.awt.Color(68, 68, 68));
        loginButton.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(244, 244, 244));
        loginButton.setText("Iniciar sesión");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        buttonsRowPanel.add(loginButton);

        registerButton.setBackground(new java.awt.Color(68, 68, 68));
        registerButton.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        registerButton.setForeground(new java.awt.Color(225, 225, 225));
        registerButton.setText("Salir");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        buttonsRowPanel.add(registerButton);

        buttonsPanel.add(buttonsRowPanel);
        buttonsPanel.add(buttonsBottomPadding);

        fieldsContainer.add(buttonsPanel);

        rightPanel.add(fieldsContainer, java.awt.BorderLayout.CENTER);

        mainPanel.add(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Por favor completa todos los campos",
                "Valdación",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            User user = controller.authenticate(username, password);
            JOptionPane.showMessageDialog(
                this,
                "¡Bienvenido " + user.getFullName() + "!",
                "Loin exitoso",
                JOptionPane.INFORMATION_MESSAGE
            );

            startMain(user);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error de autenticación",
                JOptionPane.ERROR_MESSAGE
            );
            passwordField.setText("");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler buttonsBottomPadding;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel buttonsRowPanel;
    private javax.swing.Box.Filler buttonsTopPadding;
    private javax.swing.JPanel fieldsContainer;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel rightPanel;
    private javax.swing.Box.Filler rightPanelBottomPadding;
    private javax.swing.Box.Filler rightPanelLeftPadding;
    private javax.swing.Box.Filler rightPanelRightPadding;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JSeparator titleSeparator;
    private javax.swing.Box.Filler titleTopPadding;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
