/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.edbray.pnb.gui;

import cl.edbray.pnb.model.User;
import java.awt.CardLayout;
import java.awt.GridBagLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author eduardo
 */
public class MainFrame extends javax.swing.JFrame {

    private final User currentUser;
    private CardLayout cardLayout;

    //public MainFrame(User user) {
    public MainFrame(User user) {
        currentUser = user;

        initComponents();
        setTimerHandler();
        setupNavigation(currentUser);
        applyCustomTheme();
        setupWindow();
    }

    private void setTimerHandler() {
        Timer timer = new Timer(1000, e -> {
            statusTime.setText(
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm"))
            );
        });
        timer.start();
    }

    private void setupNavigation(User user) {
        cardLayout = new CardLayout();
        mainPanel.setLayout(cardLayout);

        mainPanel.add(createHomePanel(), "HOME");
        mainPanel.add(new UsersPanel(), "USERS");
        mainPanel.add(new ProductsPanel(), "PRODUCTS");
        mainPanel.add(new EventsPanel(), "EVENTS");
        mainPanel.add(new SalesPanel(user), "SALES");
        mainPanel.add(new ReportsPanel(), "REPORTS");
        showView("HOME");
    }

    private void applyCustomTheme() {
        statusBar.setBackground(UIManager.getColor("MenuBar.background"));
        statusBar.setForeground(UIManager.getColor("MenuBar.foreground"));
        statusBar.setBorder(UIManager.getBorder("MenuBar.border"));
    }

    private void setupWindow() {
        setTitle(
            "Pixel & Bean - " + currentUser.getFullName() + " (" + currentUser.getRole() + ")"
        );
        statusUsername.setText(currentUser.getUsername());
        statusRole.setText(currentUser.getRole());
    }

    private void showView(String name) {
        cardLayout.show(mainPanel, name);
    }

    public User getCurrentUser() {
        return currentUser;
    }

    private JPanel createHomePanel() {
        JPanel homePanel = new JPanel(new GridBagLayout());
        JLabel content = new JLabel(
            "<html><center>"
            + "<h1>☕ Pixel & Beans</h1>"
            + "<p>Sistema de Gestión para <b>Café Arcade</b>.</p>"
            + "<p style='margin-top: 20px;'>Selecciona una opción del menú superior para comenzar.</p>"
            + "</center></html>"
        );

        content.setHorizontalAlignment(SwingConstants.CENTER);
        homePanel.add(content);
        return homePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        statusBar = new javax.swing.JPanel();
        leftSeparator = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0));
        statusUsernameLabel = new javax.swing.JLabel();
        statusUsername = new javax.swing.JLabel();
        separator1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 0));
        statusRoleLabel = new javax.swing.JLabel();
        statusRole = new javax.swing.JLabel();
        separator2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 0));
        statusTimeLabel = new javax.swing.JLabel();
        statusTime = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuEntryCloseSession = new javax.swing.JMenuItem();
        menuEntryQuit = new javax.swing.JMenuItem();
        menuManagement = new javax.swing.JMenu();
        menuEntryUsers = new javax.swing.JMenuItem();
        menuEntryProducts = new javax.swing.JMenuItem();
        menuOperation = new javax.swing.JMenu();
        menuEntrySales = new javax.swing.JMenuItem();
        menuReports = new javax.swing.JMenu();
        menuEntryDaySales = new javax.swing.JMenuItem();
        menuEntryTopSellers = new javax.swing.JMenuItem();
        menuEvents = new javax.swing.JMenu();
        menuEntryTournaments = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuEntryAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pixel & Bean – Sistema de Gestión");
        setPreferredSize(new java.awt.Dimension(900, 600));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        statusBar.setPreferredSize(new java.awt.Dimension(1214, 30));
        statusBar.setLayout(new javax.swing.BoxLayout(statusBar, javax.swing.BoxLayout.LINE_AXIS));
        statusBar.add(leftSeparator);

        statusUsernameLabel.setText("Usuario Activo: ");
        statusBar.add(statusUsernameLabel);

        statusUsername.setText("Nombre de usuario");
        statusBar.add(statusUsername);
        statusBar.add(separator1);

        statusRoleLabel.setText("Rol: ");
        statusBar.add(statusRoleLabel);

        statusRole.setText("Usuario");
        statusBar.add(statusRole);
        statusBar.add(separator2);

        statusTimeLabel.setText("Hora actual: ");
        statusBar.add(statusTimeLabel);
        statusBar.add(statusTime);

        getContentPane().add(statusBar, java.awt.BorderLayout.SOUTH);

        menuFile.setText("Archivo");

        menuEntryCloseSession.setLabel("Cerrar sesión");
        menuEntryCloseSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryCloseSessionActionPerformed(evt);
            }
        });
        menuFile.add(menuEntryCloseSession);

        menuEntryQuit.setLabel("Salir");
        menuEntryQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryQuitActionPerformed(evt);
            }
        });
        menuFile.add(menuEntryQuit);

        mainMenu.add(menuFile);

        menuManagement.setText("Gestión");

        menuEntryUsers.setLabel("Usuarios");
        menuEntryUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryUsersActionPerformed(evt);
            }
        });
        menuManagement.add(menuEntryUsers);

        menuEntryProducts.setLabel("Productos");
        menuEntryProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryProductsActionPerformed(evt);
            }
        });
        menuManagement.add(menuEntryProducts);

        mainMenu.add(menuManagement);

        menuOperation.setText("Operación");

        menuEntrySales.setText("Ventas");
        menuEntrySales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntrySalesActionPerformed(evt);
            }
        });
        menuOperation.add(menuEntrySales);

        mainMenu.add(menuOperation);

        menuReports.setText("Reportes");

        menuEntryDaySales.setText("Ventas del día");
        menuEntryDaySales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryDaySalesActionPerformed(evt);
            }
        });
        menuReports.add(menuEntryDaySales);

        menuEntryTopSellers.setText("Más vendidos");
        menuEntryTopSellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryTopSellersActionPerformed(evt);
            }
        });
        menuReports.add(menuEntryTopSellers);

        mainMenu.add(menuReports);

        menuEvents.setText("Eventos");

        menuEntryTournaments.setText("Torneos");
        menuEntryTournaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryTournamentsActionPerformed(evt);
            }
        });
        menuEvents.add(menuEntryTournaments);

        mainMenu.add(menuEvents);

        menuHelp.setText("Ayuda");

        menuEntryAbout.setText("Acerca de...");
        menuEntryAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuEntryAbout);

        mainMenu.add(menuHelp);

        setJMenuBar(mainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEntryCloseSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryCloseSessionActionPerformed
        int userChoice = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea cerrar la sesión?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION
        );
        if (userChoice == JOptionPane.YES_OPTION) {
            this.dispose();
            new cl.edbray.pnb.gui.LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_menuEntryCloseSessionActionPerformed

    private void menuEntryQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryQuitActionPerformed
        int userChoice = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea salir?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION
        );
        if (userChoice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuEntryQuitActionPerformed

    private void menuEntryAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryAboutActionPerformed
        JOptionPane.showMessageDialog(this,
            "<html><center>"
            + "  <h2>Pixel & Beans</h2>"
            + "  <p>Sistema de gestión para <b>Café Arcade</b>.</p>"
            + "  <p>Versión: 0.1.0</p>"
            + "  <p style='margin-top: 10px;'>Desarrollado por: Eduardo Bray</p>"
            + "  <p>Asignatura: Programación Orientada a Objetos</p>"
            + "  <p>Año: 2025</p>"
            + "</center></html>",
            "Acerda de",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_menuEntryAboutActionPerformed

    private void menuEntryUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryUsersActionPerformed
        showView("USERS");
    }//GEN-LAST:event_menuEntryUsersActionPerformed

    private void menuEntryProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryProductsActionPerformed
        showView("PRODUCTS");
    }//GEN-LAST:event_menuEntryProductsActionPerformed

    private void menuEntryTournamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryTournamentsActionPerformed
        showView("EVENTS");
    }//GEN-LAST:event_menuEntryTournamentsActionPerformed

    private void menuEntrySalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntrySalesActionPerformed

        showView("SALES");
    }//GEN-LAST:event_menuEntrySalesActionPerformed

    private void menuEntryDaySalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryDaySalesActionPerformed
        showView("REPORTS");
    }//GEN-LAST:event_menuEntryDaySalesActionPerformed

    private void menuEntryTopSellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryTopSellersActionPerformed
        showView("REPORTS");
        JOptionPane.showMessageDialog(this,
            "El reporte de productos más vendidos estará disponible a futuro",
            "En desarrollo",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuEntryTopSellersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler leftSeparator;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem menuEntryAbout;
    private javax.swing.JMenuItem menuEntryCloseSession;
    private javax.swing.JMenuItem menuEntryDaySales;
    private javax.swing.JMenuItem menuEntryProducts;
    private javax.swing.JMenuItem menuEntryQuit;
    private javax.swing.JMenuItem menuEntrySales;
    private javax.swing.JMenuItem menuEntryTopSellers;
    private javax.swing.JMenuItem menuEntryTournaments;
    private javax.swing.JMenuItem menuEntryUsers;
    private javax.swing.JMenu menuEvents;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuManagement;
    private javax.swing.JMenu menuOperation;
    private javax.swing.JMenu menuReports;
    private javax.swing.Box.Filler separator1;
    private javax.swing.Box.Filler separator2;
    private javax.swing.JPanel statusBar;
    private javax.swing.JLabel statusRole;
    private javax.swing.JLabel statusRoleLabel;
    private javax.swing.JLabel statusTime;
    private javax.swing.JLabel statusTimeLabel;
    private javax.swing.JLabel statusUsername;
    private javax.swing.JLabel statusUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
