/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cl.edbray.pnb.gui;

import cl.edbray.pnb.app.ApplicationContext;
import cl.edbray.pnb.controller.SaleController;
import cl.edbray.pnb.model.Sale;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author eduardo
 */
public class ReportsPanel extends javax.swing.JPanel {

    private final SaleController controller;

    private ReportTableModel reportTableModel;

    /**
     * Creates new form Reports
     */
    public ReportsPanel() {
        controller = ApplicationContext.getInstance().getSaleController();

        initComponents();
        setupComponents();
    }

    private void setupComponents() {
        reportTableModel = new ReportTableModel();
        tableReport.setModel(reportTableModel);

        setFilters();
        setupListeners();
        loadTodaySales();
        updateReport();
    }

    private void setFilters() {
        comboFilter.addItem("Hoy");
        comboFilter.addItem("Ayer");
        comboFilter.addItem("Última semana");
        comboFilter.addItem("Último mes");
        comboFilter.addItem("Histórico");
    }

    private void setupListeners() {
        comboFilter.addActionListener(e -> {
            updateReport();
        });
    }

    private void loadTodaySales() {
        reportTableModel.setSells(controller.listToday());
    }

    private LocalDateTime[] getFilterRangeDates(int filter) {
        LocalDateTime today = LocalDate.now().atStartOfDay();
        LocalDateTime todayEnd = today.plusDays(1);

        return switch (filter) {
            case 1 ->
                new LocalDateTime[]{today.minusDays(1), today};
            case 2 ->
                new LocalDateTime[]{today.minusWeeks(1), todayEnd};
            case 3 ->
                new LocalDateTime[]{today.minusMonths(1), todayEnd};
            case 4 ->
                new LocalDateTime[]{LocalDateTime.MIN, todayEnd};
            default ->
                new LocalDateTime[]{today, todayEnd};
        };
    }

    private void updateReport() {
        int selectedFilter = comboFilter.getSelectedIndex();
        LocalDateTime[] range = getFilterRangeDates(selectedFilter);

        reportTableModel.setSells(controller.listByDateRange(range[0], range[1]));
        double total = controller.calculateTotalByRange(range[0], range[1]);
        labelTotal.setText(String.format("Total: $%,.0f", total));
    }

    private void generateReport() {
        String range = comboFilter.getSelectedItem().toString();
        JOptionPane.showMessageDialog(
            this,
            "Se ha generado exitosamente el reporte de ventas (" + range + ").",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        comboFilter = new javax.swing.JComboBox<>();
        buttonGenerate = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        tablePane = new javax.swing.JScrollPane();
        tableReport = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(900, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        layout.columnWeights = new double[] {1.0};
        layout.rowWeights = new double[] {0.1};
        setLayout(layout);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        add(comboFilter, gridBagConstraints);

        buttonGenerate.setText("Generar");
        buttonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(buttonGenerate, gridBagConstraints);

        labelTotal.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        labelTotal.setText("Total:");
        labelTotal.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 25, 3, 3);
        add(labelTotal, gridBagConstraints);

        tableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Nombre de Usuario", "Total", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableReport.setFillsViewportHeight(true);
        tableReport.setShowGrid(false);
        tableReport.getTableHeader().setReorderingAllowed(false);
        tablePane.setViewportView(tableReport);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(tablePane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateActionPerformed
        generateReport();
    }//GEN-LAST:event_buttonGenerateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGenerate;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JScrollPane tablePane;
    private javax.swing.JTable tableReport;
    // End of variables declaration//GEN-END:variables

    private class ReportTableModel extends AbstractTableModel {

        private List<Sale> sells = new ArrayList<>();
        private final String[] columnNames = {"ID", "Fecha/Hora", "Usuario", "Total", "Estado"};

        public void setSells(List<Sale> sells) {
            this.sells = sells;
            fireTableDataChanged();
        }

        @Override
        public int getRowCount() {
            return sells.size();
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }

        @Override
        public Object getValueAt(int row, int column) {
            Sale s = sells.get(row);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            return switch (column) {
                case 0 ->
                    s.getId();
                case 1 ->
                    s.getDateTime().format(formatter);
                case 2 ->
                    s.getUserName();
                case 3 ->
                    String.format("$%,.0f", s.getTotal());
                case 4 ->
                    s.getState();
                default ->
                    null;
            };
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }
}
