/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cl.edbray.pnb.gui;

import cl.edbray.pnb.model.Product;
import cl.edbray.pnb.model.Sale;
import cl.edbray.pnb.service.ProductsService;
import cl.edbray.pnb.service.SalesService;
import cl.edbray.pnb.service.impl.ProductsServiceStub;
import cl.edbray.pnb.service.impl.SalesServiceStub;
import java.awt.Component;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author eduardo
 */
public class SalesPanel extends javax.swing.JPanel {
    private final ProductsService productsService;
    private final SalesService salesService;

    private SalesTableModel salesTableModel;
    private SalesDetailsTableModel detailsTableModel;
    private DefaultListModel<Product> productsListModel;

    private List<SaleItem> saleItems;

    /**
     * Creates new form salePanel
     */
    public SalesPanel() {
        productsService = new ProductsServiceStub();
        salesService = new SalesServiceStub();

        initComponents();
        setupComponents();
        loadProducts();
        loadDaySales();
        customizeTables();
    }

    private void setupComponents() {
        productsListModel = new DefaultListModel<>();
        productList.setModel(productsListModel);
        productList.setCellRenderer(new ProductListCellRenderer());

        amountSpinner.setModel(new SpinnerNumberModel(1, 1, 99, 1));

        saleItems = new ArrayList<>();
        detailsTableModel = new SalesDetailsTableModel();
        detailsTable.setModel(detailsTableModel);

        salesTableModel = new SalesTableModel();
        historyTable.setModel(salesTableModel);

        updateTotal();
    }

    private void customizeTables() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        historyTable.setDefaultRenderer(Object.class, centerRenderer);
        historyTable.getColumnModel().getColumn(0).setMaxWidth(75);
        historyTable.getColumnModel().getColumn(4).setMaxWidth(125);

        detailsTable.setDefaultRenderer(Object.class, centerRenderer);
    }

    private void loadProducts() {
        productsListModel.clear();
        productsService.listAll()
            .forEach(productsListModel::addElement);
    }

    private void loadDaySales() {
        salesTableModel.setSales(salesService.listTodaySales());
        double total = salesService.calculateTotalByDate(LocalDate.now());
        dailyTotalField.setText(String.format("Total del día: $%,.0f", total));
    }

    private void cleanSale() {
        saleItems.clear();
        detailsTableModel.fireTableDataChanged();
        updateTotal();
        productList.clearSelection();
        amountSpinner.setValue(1);
    }

    private double calculateTotal() {
        return saleItems.stream()
            .mapToDouble(SaleItem::getSubTotal)
            .sum();
    }

    private void updateTotal() {
        double total = calculateTotal();
        totalField.setText(String.format("TOTAL: $%,.0f", total));
    }

    private void filterProducts(String search) {
        search = search.trim();
        productsListModel.clear();
        productsService.searchByName(search)
            .forEach(productsListModel::addElement);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchListPanel = new javax.swing.JScrollPane();
        productList = new javax.swing.JList<>();
        amountLabel = new javax.swing.JLabel();
        amountSpinner = new javax.swing.JSpinner();
        addButton = new javax.swing.JButton();
        detailsPanel = new javax.swing.JPanel();
        detailsPanelTitleLabel = new javax.swing.JLabel();
        detailsTablePanel = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        removeButton = new javax.swing.JButton();
        totalField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        historyPanel = new javax.swing.JPanel();
        historyPanelTitleLabel = new javax.swing.JLabel();
        historyTablePanel = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        dailyTotalField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0};
        setLayout(layout);

        titlePanel.setLayout(new java.awt.GridLayout(1, 0));

        titleLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        titleLabel.setText("Registro de Nueva Venta");
        titlePanel.add(titleLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.weighty = 0.01;
        add(titlePanel, gridBagConstraints);

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        searchPanel.setLayout(jPanel2Layout);

        searchLabel.setText("Buscar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        searchPanel.add(searchLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        searchPanel.add(searchField, gridBagConstraints);

        searchButton.setText("🔍");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        searchPanel.add(searchButton, gridBagConstraints);

        searchListPanel.setViewportView(productList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        searchPanel.add(searchListPanel, gridBagConstraints);

        amountLabel.setText("Cantidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        searchPanel.add(amountLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        searchPanel.add(amountSpinner, gridBagConstraints);

        addButton.setText("Agregar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        searchPanel.add(addButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        add(searchPanel, gridBagConstraints);

        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 10, 0};
        jPanel3Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        detailsPanel.setLayout(jPanel3Layout);

        detailsPanelTitleLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        detailsPanelTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailsPanelTitleLabel.setText("Detalle de la Venta");
        detailsPanelTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        detailsPanel.add(detailsPanelTitleLabel, gridBagConstraints);

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        detailsTable.setPreferredSize(new java.awt.Dimension(300, 100));
        detailsTablePanel.setViewportView(detailsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        detailsPanel.add(detailsTablePanel, gridBagConstraints);

        removeButton.setText("Quitar Seleccionado");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        detailsPanel.add(removeButton, gridBagConstraints);

        totalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalField.setText("Total: $7.000");
        totalField.setEnabled(false);
        totalField.setMinimumSize(new java.awt.Dimension(125, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        detailsPanel.add(totalField, gridBagConstraints);

        confirmButton.setText("Confirmar Venta");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        detailsPanel.add(confirmButton, gridBagConstraints);

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        detailsPanel.add(cancelButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.6;
        add(detailsPanel, gridBagConstraints);

        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0};
        jPanel4Layout.rowHeights = new int[] {0, 10, 0, 10, 0};
        historyPanel.setLayout(jPanel4Layout);

        historyPanelTitleLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        historyPanelTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyPanelTitleLabel.setText("Ventas del día");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        historyPanel.add(historyPanelTitleLabel, gridBagConstraints);

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Fecha/Hora", "Usuario", "Total", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historyTable.getTableHeader().setReorderingAllowed(false);
        historyTablePanel.setViewportView(historyTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        historyPanel.add(historyTablePanel, gridBagConstraints);

        dailyTotalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dailyTotalField.setText("Total del día: $12.500");
        dailyTotalField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        historyPanel.add(dailyTotalField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(historyPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Product selection = productList.getSelectedValue();
        if (selection == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto",
                "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int amount = (Integer) amountSpinner.getValue();
        boolean found = false;
        for (SaleItem item : saleItems) {
            if (item.getProduct().getId() == selection.getId()) {
                item.setAmount(item.getAmount() + amount);
                found = true;
                break;
            }
        }

        if (!found) {
            saleItems.add(new SaleItem(selection, amount));
        }

        detailsTableModel.fireTableDataChanged();
        updateTotal();
        amountSpinner.setValue(1);

    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int selectedRow = detailsTable.getSelectedRow();
        if (selectedRow >= 0) {
            saleItems.remove(selectedRow);
            detailsTableModel.fireTableDataChanged();
            updateTotal();
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (saleItems.isEmpty()) { return; }

        int answer = JOptionPane.showConfirmDialog(
            this,
           "¿Cancelar la venta actual?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION
        );

        if (answer == JOptionPane.YES_OPTION) {
             cleanSale();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (saleItems.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Agrega al menos un producto",
                "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double total = calculateTotal();
        int answer = JOptionPane.showConfirmDialog(
            this,
            String.format("¿Confirmar venta por $%,.0f", total),
            "Confirmar Venta",
            JOptionPane.YES_NO_OPTION
        );

        if (answer == JOptionPane.YES_OPTION) {
            // TODO: get user from login
            int userId = 9999;
            String userName = "Placeholder";
            Sale sale = new Sale(
                0, LocalDateTime.now(), userId, userName, total, "ACTIVA"
            );

            salesService.save(sale);
            JOptionPane.showMessageDialog(this, "Venta registrada exitosamente");
            cleanSale();
        }

        loadDaySales();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        filterProducts(searchField.getText());
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField dailyTotalField;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel detailsPanelTitleLabel;
    private javax.swing.JTable detailsTable;
    private javax.swing.JScrollPane detailsTablePanel;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JLabel historyPanelTitleLabel;
    private javax.swing.JTable historyTable;
    private javax.swing.JScrollPane historyTablePanel;
    private javax.swing.JList<Product> productList;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JScrollPane searchListPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables

    private class SaleItem {
        private Product product;
        private int amount;

        public SaleItem(Product product, int amount) {
            this.product = product;
            this.amount = amount;
        }

        public Product getProduct() { return product; }
        public int getAmount() { return amount; }
        public void setAmount(int amount) { this.amount = amount; }
        public double getSubTotal() { return product.getPrice() * amount; }
    }

    private class SalesDetailsTableModel extends AbstractTableModel {
        private String[] columnNames = {"Producto", "Cantidad", "Precio Unit.", "Subtotal"};

        @Override
        public int getRowCount() { return saleItems.size(); }

        @Override
        public int getColumnCount() { return columnNames.length; }

        @Override
        public String getColumnName(int column) { return columnNames[column]; }

        @Override
        public Object getValueAt(int row, int column) {
            SaleItem item = saleItems.get(row);
            return switch (column) {
                case 0 -> item.getProduct().getName();
                case 1 -> item.getAmount();
                case 2 -> String.format("$%,.0f", item.getProduct().getPrice());
                case 3 -> String.format("$%,.0f", item.getSubTotal());
                default -> null;
            };
        }

        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    }

    private class SalesTableModel extends AbstractTableModel {
        private List<Sale> sales = new ArrayList<>();
        private final String[] columnNames = {"#", "Fecha/Hora", "Usuario", "Total", "Estado"};

        public void setSales(List<Sale> sales) {
            this.sales = sales;
            fireTableDataChanged();
        }

        @Override
        public int getRowCount() { return sales.size(); }

        @Override
        public int getColumnCount() { return columnNames.length; }

        @Override
        public String getColumnName(int column) { return columnNames[column]; }

        @Override
        public Object getValueAt(int row, int column) {
            Sale s = sales.get(row);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yy HH:MM");
            return switch (column) {
                case 0 -> s.getId();
                case 1 -> s.getDateTime().format(formatter);
                case 2 -> s.getUserName();
                case 3 -> String.format("$%,.0f", s.getTotal());
                case 4 -> s.getState();
                default -> null;
            };
        }

        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    }

    private class ProductListCellRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value,
            int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            if (value instanceof Product) {
                Product p = (Product) value;
                setText(String.format("<html><b>%s</b><br><small>$%,.0f</small></html>",
                    p.getName(), p.getPrice()));
            }

            return this;
        };
    }
}
