/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cl.edbray.pnb.gui;

import cl.edbray.pnb.model.User;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author eduardo
 */
public class UsersPanel extends javax.swing.JPanel {

    private User selectedUser;
    private UserTableModel tableModel;

    /**
     * Creates new form UsersPanel
     */
    public UsersPanel() {
        initComponents();
        setupTable();
        setupListeners();
        loadUsers();
    }

    private void setupTable() {
        tableModel = new UserTableModel();
        usersTable.setModel(tableModel);
        usersTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        usersTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        usersTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        usersTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        usersTable.getColumnModel().getColumn(3).setPreferredWidth(80);
        usersTable.getColumnModel().getColumn(4).setPreferredWidth(60);
    }

    private void setupListeners() {
        usersTable.getSelectionModel().addListSelectionListener(ev -> {
            if (!ev.getValueIsAdjusting()) {
                int selectedRow = usersTable.getSelectedRow();
                if (selectedRow >= 0) {
                    selectedUser = tableModel.getUserAt(selectedRow);
                    loadInForm(selectedUser);
                }
            }
        });

        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent ev) {
                if (ev.getClickCount() == 2) {
                    int row = usersTable.getSelectedRow();
                    if (row >= 0) {
                        selectedUser = tableModel.getUserAt(row);
                        loadInForm(selectedUser);
                        usernameField.requestFocus();
                    }
                }
            }
        });
    }

    private void loadInForm(User user) {
        usernameField.setText(user.getUsername());
        passwordField.setText(user.getPassword());
        fullNameField.setText(user.getFullName());
        roleComboBox.setSelectedItem(user.getRole());
        activeCheck.setSelected(user.isActive());

        deleteButton.setEnabled(true);
    }

    private void loadUsers() {
        List<User> users = new ArrayList<>();
        users.add(new User(1, "admin", "admin123", "Administrador del Sistema", "ADMIN", true));
        users.add(new User(2, "operador", "op123", "Juan Pérez", "OPERADOR", true));
        users.add(new User(3, "cajero", "caj123", "María González", "OPERADOR", true));

        tableModel.setUsers(users);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        searchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        newUserButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        formPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        fullNameLabel = new javax.swing.JLabel();
        fullNameField = new javax.swing.JTextField();
        roleLabel = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        activeCheck = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 7, 10, 7));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout(10, 10));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        searchPanel.setLayout(flowLayout1);

        searchLabel.setText("Buscar:");
        searchPanel.add(searchLabel);

        searchField.setPreferredSize(new java.awt.Dimension(300, 23));
        searchPanel.add(searchField);

        newUserButton.setText("Nuevo Usuario");
        searchPanel.add(newUserButton);

        add(searchPanel, java.awt.BorderLayout.PAGE_START);

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePanel.setViewportView(usersTable);

        add(tablePanel, java.awt.BorderLayout.CENTER);

        formPanel.setLayout(new java.awt.GridLayout(3, 4, 15, 7));

        usernameLabel.setText("Usuario:");
        formPanel.add(usernameLabel);
        formPanel.add(usernameField);

        passwordLabel.setText("Contraseña");
        formPanel.add(passwordLabel);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        formPanel.add(passwordField);

        fullNameLabel.setText("Nombre completo:");
        formPanel.add(fullNameLabel);
        formPanel.add(fullNameField);

        roleLabel.setText("Rol:");
        formPanel.add(roleLabel);

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "OPERADOR" }));
        formPanel.add(roleComboBox);

        activeCheck.setText("Usuario activo");
        formPanel.add(activeCheck);

        saveButton.setText("Guardar");
        formPanel.add(saveButton);

        cancelButton.setText("Cancelar");
        formPanel.add(cancelButton);

        deleteButton.setText("Eliminar");
        formPanel.add(deleteButton);

        add(formPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activeCheck;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JButton newUserButton;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables

    private class UserTableModel extends AbstractTableModel {
        private List<User> users = new ArrayList<>();
        private String[] columnNames = { "ID", "Usuario", "Nombre completo", "Rol", "Activo" };

        public void setUsers(List<User> users) {
            this.users = users;
            fireTableDataChanged();
        }

        public User getUserAt(int row) {
            return users.get(row);
        }

        @Override
        public int getRowCount() {
            return users.size();
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

        @Override
        public Object getValueAt(int row, int column) {
            User user = users.get(row);
            return switch (column) {
                case 0 -> user.getId();
                case 1 -> user.getUsername();
                case 2 -> user.getFullName();
                case 3 -> user.getRole();
                case 4 -> user.isActive() ? "Sí" : "No";
                default -> null;
            };
        }
    }
}
